def get_sample_data():
    # Large dataset with 80 reviews (40 positive, 40 negative)
    # More vocabulary diversity to help model generalize
    reviews = [
        # Positive reviews (label = 1)
        ("This movie was absolutely amazing and fantastic", 1),
        ("Great film with wonderful acting and story", 1),
        ("Loved every minute of this incredible movie", 1),
        ("Best cinema experience I have had in years", 1),
        ("Outstanding performance by all the actors", 1),
        ("Brilliant direction and excellent screenplay", 1),
        ("This film exceeded all my expectations completely", 1),
        ("Amazing cinematography and beautiful visuals throughout", 1),
        ("Perfect movie for the whole family to enjoy", 1),
        ("Incredible story that kept me engaged throughout", 1),
        ("Wonderful characters and amazing plot development", 1),
        ("This movie is a true masterpiece of cinema", 1),
        ("Excellent acting and superb direction combined perfectly", 1),
        ("Beautiful story with great emotional depth", 1),
        ("Amazing special effects and fantastic action sequences", 1),
        ("This film is definitely worth watching multiple times", 1),
        ("Great movie with incredible character development", 1),
        ("Loved the humor and excellent dialogue", 1),
        ("Outstanding cinematography and beautiful soundtrack", 1),
        ("This movie was entertaining from start to finish", 1),
        ("Brilliant performance by the lead actor", 1),
        ("Amazing story with unexpected twists and turns", 1),
        ("Great film with excellent production values", 1),
        ("This movie has everything you want in cinema", 1),
        ("Wonderful adaptation of the original source material", 1),
        ("Excellent movie with great replay value", 1),
        ("Amazing direction and fantastic camera work", 1),
        ("This film is a perfect example of great storytelling", 1),
        ("Great characters and wonderful emotional moments", 1),
        ("Brilliant movie with excellent pacing throughout", 1),
        ("This cinema experience was absolutely incredible", 1),
        ("Amazing film with great attention to detail", 1),
        ("Excellent movie that deserves all the praise", 1),
        ("Great story with wonderful character arcs", 1),
        ("This movie is entertaining and well made", 1),
        ("Brilliant acting and excellent supporting cast", 1),
        ("Amazing movie with great visual effects", 1),
        ("This film is a joy to watch", 1),
        ("Excellent screenplay and wonderful direction", 1),
        ("Great movie that I would highly recommend", 1),

        # Negative reviews (label = 0)
        ("This movie was absolutely terrible and boring", 0),
        ("Worst film I have ever seen in theaters", 0),
        ("Hated every minute of this awful movie", 0),
        ("Bad cinema experience with poor acting", 0),
        ("Terrible performance by all the actors involved", 0),
        ("Poor direction and awful screenplay throughout", 0),
        ("This film disappointed me in every way", 0),
        ("Horrible cinematography and ugly visuals", 0),
        ("Boring movie that wasted my time completely", 0),
        ("Terrible story that made no sense", 0),
        ("Awful characters and poor plot development", 0),
        ("This movie is a complete disaster", 0),
        ("Bad acting and terrible direction combined poorly", 0),
        ("Boring story with no emotional depth", 0),
        ("Terrible special effects and awful action sequences", 0),
        ("This film is definitely not worth watching", 0),
        ("Bad movie with horrible character development", 0),
        ("Hated the humor and terrible dialogue", 0),
        ("Poor cinematography and annoying soundtrack", 0),
        ("This movie was boring from start to finish", 0),
        ("Terrible performance by the lead actor", 0),
        ("Awful story with predictable and boring twists", 0),
        ("Bad film with poor production values", 0),
        ("This movie has nothing good about it", 0),
        ("Terrible adaptation that ruined the original", 0),
        ("Awful movie with no redeeming qualities", 0),
        ("Bad direction and horrible camera work", 0),
        ("This film is a terrible example of poor storytelling", 0),
        ("Bad characters and awful emotional moments", 0),
        ("Horrible movie with terrible pacing throughout", 0),
        ("This cinema experience was absolutely awful", 0),
        ("Terrible film with poor attention to detail", 0),
        ("Bad movie that deserves all the criticism", 0),
        ("Awful story with horrible character development", 0),
        ("This movie is boring and poorly made", 0),
        ("Terrible acting and awful supporting cast", 0),
        ("Bad movie with horrible visual effects", 0),
        ("This film is painful to watch", 0),
        ("Terrible screenplay and poor direction", 0),
        ("Bad movie that I would never recommend", 0),
    ]
    return reviews

# Sample data that the model is not trained on
def get_untrained_reviews():
    # Format: (review_text, label)
    # 1 = positive, 0.5 = neutral, 0 = bad
    reviews = [
        ("This was a good piece of cinema.", 1),
        ("Not good, but not bad.", 0.5),
        ("What a bad no good horrible movie.", 0),
        ("Was a great movie 10/10.", 1),
    ]
    return reviews